### ISSUE TITLE
PYTHON_DEST is not set to the install directory

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF-SuperBuild#52] opened 2017-10-31 08:57 UTC
[`PYTHON_DEST`](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild/External_SIRF.cmake#L45) does not point to the same directory as [`PYTHONPATH`](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/env_ccppetmr.sh.in#L17)

**Comment by paskino** [comment] 2017-11-19 08:17
This issue is a CMake cache issue.

**Comment by evgueni-ovtchinnikov** [comment] 2017-11-20 11:17
I just have downloaded and imported again SIRF_0.9.2_Ubuntu16.04_VM, run update_VM.sh and ccmake after configuring showed PYTHON_DEST to be /home/surfuser/devel/SIRF-SuperBuild/INSTALL/python, whereas PYTHONPATH is /home/surfuser/devel/install/python.

So, the issue is apparently still there ☹.

**Comment by paskino** [comment] 2017-12-13 23:57
Is this still relevant?

**Comment by evgueni-ovtchinnikov** [comment] 2017-12-14 11:04
For the current VM, it is. But you were going to make a new one, were you not?

**Comment by KrisThielemans** [comment] 2018-01-12 23:34
should all be fixed now, especially with #66.

**Closed by KrisThielemans** 2018-01-12 23:34 UTC
Labels: bug
