### ISSUE TITLE
CMAKE_BUILD_TYPE is not set in child projects

### ISSUE THREAD

**Issue by ALEXJAZZ008008** [CCPPETMR/SIRF-SuperBuild#315] opened 2020-02-03 16:48 UTC
if CMAKE_BUILD_TYPE is set to anything other than Release then the build type will not propagate to the 'child' builds of the super build and they will instead be built in Release. Not as easy to debug etc like this.

**Comment by KrisThielemans** [comment] 2020-03-14 17:20
Duplicate of #301

**Closed by KrisThielemans** 2020-03-14 17:20 UTC
